In [1]:
data = [[1,2],[3,4]]
data

[[1, 2], [3, 4]]

In [2]:
import torch

In [3]:
x_data  = torch.tensor(data)

In [4]:
import numpy as np

In [5]:
np_data = np.array(data)
np_data

array([[1, 2],
       [3, 4]])

In [6]:
torch.from_numpy(np_data)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [7]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [8]:
torch.rand_like(x_data,dtype=torch.float)

tensor([[0.2110, 0.6995],
        [0.3320, 0.5425]])

In [9]:
shape = (2,3)
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(shape)

tensor([[0.3596, 0.2856, 0.2671],
        [0.1709, 0.0360, 0.9702]])

In [11]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
ten  = torch.rand(3,4)

In [13]:
ten

tensor([[0.8180, 0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785]])

In [14]:
ten.shape

torch.Size([3, 4])

In [15]:
ten.dtype

torch.float32

In [16]:
ten.device

device(type='cpu')

In [17]:
ten.data

tensor([[0.8180, 0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785]])

In [18]:
ten.numpy()

array([[0.81802094, 0.41466677, 0.7044461 , 0.9121079 ],
       [0.95952857, 0.62148136, 0.1863023 , 0.99551237],
       [0.78912276, 0.63500124, 0.19490123, 0.87853986]], dtype=float32)

## tensor的索引

In [19]:
ten

tensor([[0.8180, 0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785]])

In [20]:
ten[0]

tensor([0.8180, 0.4147, 0.7044, 0.9121])

In [21]:
ten[:,0]

tensor([0.8180, 0.9595, 0.7891])

In [22]:
ten[0,0]

tensor(0.8180)

In [23]:
torch.cat([ten,ten,ten],dim=0) #在行上进行堆叠

tensor([[0.8180, 0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785],
        [0.8180, 0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785],
        [0.8180, 0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785]])

In [24]:
torch.cat([ten,ten,ten],dim=1) #在列上进行堆叠

tensor([[0.8180, 0.4147, 0.7044, 0.9121, 0.8180, 0.4147, 0.7044, 0.9121, 0.8180,
         0.4147, 0.7044, 0.9121],
        [0.9595, 0.6215, 0.1863, 0.9955, 0.9595, 0.6215, 0.1863, 0.9955, 0.9595,
         0.6215, 0.1863, 0.9955],
        [0.7891, 0.6350, 0.1949, 0.8785, 0.7891, 0.6350, 0.1949, 0.8785, 0.7891,
         0.6350, 0.1949, 0.8785]])

In [25]:
ten = torch.tensor([[1,2],[2,3]])
ten

tensor([[1, 2],
        [2, 3]])

In [26]:
ten * ten #将数据看作数组进行乘法

tensor([[1, 4],
        [4, 9]])

In [27]:
ten @ ten #将数据看作是矩阵进行乘法

tensor([[ 5,  8],
        [ 8, 13]])

In [28]:
ten.matmul(ten) #将数据看作是矩阵进行乘法

tensor([[ 5,  8],
        [ 8, 13]])

In [29]:
agg = ten.sum()
agg

tensor(8)

In [30]:
agg.item()

8

In [31]:
type(agg.item) #item将数据转为python内置的数据类型

builtin_function_or_method

In [32]:
ten

tensor([[1, 2],
        [2, 3]])

In [33]:
ten.add(5)

tensor([[6, 7],
        [7, 8]])

In [34]:
ten  #这里的ten值不变

tensor([[1, 2],
        [2, 3]])

In [35]:
out = ten.add_(5) #原位操作，改变原来的值
out

tensor([[6, 7],
        [7, 8]])

In [36]:
ten

tensor([[6, 7],
        [7, 8]])

In [37]:
ten.numpy() #tensor转为numpy数据类型

array([[6, 7],
       [7, 8]], dtype=int64)

In [38]:
np_data = np.array([[1,2],[3,4]])
np_data

array([[1, 2],
       [3, 4]])

In [40]:
torch.from_numpy(np_data) #从numpy数据类型转为tensor类型

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)